export const BEDWARS = {
		TITLE : 'Bed Wars',
		EASY_XP: [500, 1000, 2000, 3500],
		NORMAL_XP: 5000,
		PRESTIGES: [
			{level: 0, colormap: '7', color: 'gray', name: 'None'},
			{level: 100, colormap: 'f', color: 'white', name: 'Iron'},
			{level: 200, colormap: '6', color: 'gold', name: 'Gold'},
			{level: 300, colormap: 'b', color: 'aqua', name: 'Diamond'},
			{level: 400, colormap: '2', color: 'darkgreen', name: 'Emerald'},
			{level: 500, colormap: '3', color: 'darkaqua', name: 'Sapphire'},
			{level: 600, colormap: '4', color: 'darkred', name: 'Ruby'},
			{level: 700, colormap: 'd', color: 'pink', name: 'Crystal'},
			{level: 800, colormap: '9', color: 'blue', name: 'Opal'},
			{level: 900, colormap: '5', color: 'purple', name: 'Amethyst'},
			{level: 1000, colormap: 'c6eabd5', color: 'rainbow', name: 'Rainbow'},
			{level: 1100, colormap: '7ffff77', color: 'white', name: 'Iron Prime'},
			{level: 1200, colormap: '7eeee67', color: 'yellow', name: 'Gold Prime'},
			{level: 1300, colormap: '7bbbb37', color: 'aqua', name: 'Diamond Prime'},
			{level: 1400, colormap: '7aaaa27', color: 'green', name: 'Emerald Prime'},
			{level: 1500, colormap: '7333397', color: 'darkaqua', name: 'Sapphire Prime'},
			{level: 1600, colormap: '7cccc47', color: 'red', name: 'Ruby Prime'},
			{level: 1700, colormap: '7dddd57', color: 'pink', name: 'Crystal Prime'},
			{level: 1800, colormap: '7999917', color: 'blue', name: 'Opal Prime'},
			{level: 1900, colormap: '7555587', color: 'purple', name: 'Amethyst Prime'},
			{level: 2000, colormap: '87ff778', color: 'white', name: 'Mirror'},
			{level: 2100, colormap: 'ffee666', color: 'yellow', name: 'Light'},
			{level: 2200, colormap: '66ffb33', color: 'aqua', name: 'Dawn'},
			{level: 2300, colormap: '55dd6ee', color: 'purple', name: 'Dusk'},
			{level: 2400, colormap: 'bbff778', color: 'white', name: 'Air'},
			{level: 2500, colormap: 'ffaa222', color: 'green', name: 'Wind'},
			{level: 2600, colormap: '44ccdd5', color: 'darkred', name: 'Nebula'},
			{level: 2700, colormap: 'eeff777', color: 'yellow', name: 'Thunder'},
			{level: 2800, colormap: 'aa2266e', color: 'darkgreen', name: 'Earth'},
			{level: 2900, colormap: 'bb33991', color: 'blue', name: 'Water'},
			{level: 3000, colormap: 'ee66cc4', color: 'red', name: 'Fire'},
		],
		PRESTIGE_ICONS: [
			{level: 0, symbol: '✫'},
			{level: 1100, symbol: '✪'},
			{level: 2100, symbol: '⚝'},
		],
		MODES : [
			{id: 'eight_one_', name: 'Solo'},
			{id: 'eight_two_', name: 'Doubles'},
			{id: 'four_three_', name: '3v3v3v3'},
			{id: 'four_four_', name: '4v4v4v4'},
			{id: 'two_four_', name: '4v4'},
			{id: '', name: 'Overall'},
			{id: 'eight_one_rush_', name: 'Rush Solo'},
			{id: 'eight_two_rush_', name: 'Rush Doubles'},
			{id: 'four_four_rush_', name: 'Rush 4v4v4v4'},
			{id: 'eight_one_ultimate_', name: 'Ultimate Solo'},
			{id: 'eight_two_ultimate_', name: 'Ultimate Doubles'},
			{id: 'four_four_ultimate_', name: 'Ultimate 4v4v4v4'},
			{id: 'eight_two_lucky_', name: 'Lucky Doubles'},
			{id: 'four_four_lucky_', name: 'Lucky 4v4v4v4'},
			{id: 'eight_two_voidless_', name: 'Voidless Doubles'},
			{id: 'four_four_voidless_', name: 'Voidless 4v4v4v4'},
			{id: 'eight_two_armed_', name: 'Armed Doubles'},
			{id: 'four_four_armed_', name: 'Armed 4v4v4v4'},
			{id: 'castle_', name: 'Castle'},
		],
	};