export const BLITZSG = {
	TITLE: 'Blitz SG',
	KITS: [
		{id: 'arachnologist', name: 'Arachnologist'},
		{id: 'archer', name: 'Archer'},
		{id: 'armorer', name: 'Armorer'},
		{id: 'astronaut', name: 'Astronaut'},
		{id: 'baker', name: 'Baker'},
		{id: 'blaze', name: 'Blaze'},
		{id: 'creepertamer', name: 'Creepertamer'},
		{id: 'diver', name: 'Diver'},
		{id: 'donkeytamer', name: 'Donkeytamer'},
		{id: 'farmer', name: 'Farmer'},
		{id: 'florist', name: 'Florist'},
		{id: 'golem', name: 'Golem'},
		{id: 'guardian', name: 'Guardian'},
		{id: 'horsetamer', name: 'Horsetamer'},
		{id: 'hunter', name: 'Hunter'},
		{id: 'hype train', name: 'Hype Train'},
		{id: 'jockey', name: 'Jockey'},
		{id: 'knight', name: 'Knight'},
		{id: 'meatmaster', name: 'Meatmaster'},
		{id: 'necromancer', name: 'Necromancer'},
		{id: 'paladin', name: 'Paladin'},
		{id: 'phoenix', name: 'Phoenix'},
		{id: 'pigman', name: 'Pigman'},
		{id: 'ranger', name: 'Ranger'},
		{id: 'reaper', name: 'Reaper'},
		{id: 'reddragon', name: 'Red Dragon'},
		{id: 'rogue', name: 'Rogue'},
		{id: 'scout', name: 'Scout'},
		{id: 'shadow knight', name: 'Shadow Knight'},
		{id: 'slimeyslime', name: 'Slimey Slime'},
		{id: 'snowman', name: 'Snowman'},
		{id: 'speleologist', name: 'Speleologist'},
		{id: 'tim', name: 'Tim'},
		{id: 'toxicologist', name: 'Toxicologist'},
		{id: 'troll', name: 'Troll'},
		{id: 'viking', name: 'Viking'},
		{id: 'warlock', name: 'Warlock'},
		{id: 'warrior', name: 'Warrior'},
		{id: 'wolftamer', name: 'Wolftamer'},
	],
	MODES: [
		{id: 'solo_normal', name: 'Solo Normal'},
		{id: 'teams_normal', name: 'Teams Normal'},
	],
	KITEXP: [ 0, 100, 250, 500, 1000, 1500, 2000, 2500, 5000, 10000 ],
}