export const BUILDBATTLE = {
		TITLE: 'Build Battle',
		MODES: [
			{id: '_solo_normal', name: 'Solo'},
			{id: '_teams_normal', name: 'Teams'},
			{id: '_guess_the_build', name: 'Guess the Build'},
			{id: '_solo_pro', name: 'Pro'},
			{id: '_speed_builders', name: 'Speed Builders'},
			{id: '', name: 'Overall'},
		],
		STARS: [
			{value: 0, name: 'Rookie', color: 'white'},
			{value: 100, name: 'Untrained', color: 'gray'},
			{value: 250, name: 'Amateur', color: 'darkgray'},
			{value: 500, name: 'Prospect', color: 'green'},
			{value: 1000, name: 'Apprentice', color: 'darkgreen'},
			{value: 2000, name: 'Experienced', color: 'aqua'},
			{value: 3500, name: 'Seasoned', color: 'darkaqua'},
			{value: 5000, name: 'Trained', color: 'blue'},
			{value: 7500, name: 'Skilled', color: 'darkblue'},
			{value: 10000, name: 'Talented', color: 'purple'},
			{value: 15000, name: 'Professional', color: 'pink'},
			{value: 20000, name: 'Artisan', color: 'red'},
			{value: 30000, name: 'Expert', color: 'darkred'},
			{value: 50000, name: 'Master', color: 'gold'},
			{value: 100000, name: 'Legend', color: 'green'},
			{value: 200000, name: 'Grandmaster', color: 'aqua'},
			{value: 300000, name: 'Celestial', color: 'pink'},
			{value: 400000, name: 'Divine', color: 'red'},
			{value: 500000, name: 'Ascended', color: 'gold'},
			{value: Infinity, name: 'Ascended', color: 'gold'}
		],
	}