export const DUELS = {
	TITLE: 'Duels',
	DIVISIONS: [
		{name: 'Rookie',      color: 'darkgray',  style: '§8' },
		{name: 'Iron',        color: 'white',     style: '§f' },
		{name: 'Gold',        color: 'gold',      style: '§6' },
		{name: 'Diamond',     color: 'aqua',      style: '§b' },
		{name: 'Master',      color: 'darkgreen', style: '§2' },
		{name: 'Legend',      color: 'darkred',   style: '§4' },
		{name: 'Grandmaster', color: 'yellow',    style: '§e§l' },
		{name: 'Godlike',     color: 'purple',    style: '§5§l' },
	],
	MODES: [
		{id: 'uhc_duel_', divisionId: 'uhc', name: 'UHC 1v1'},
		{id: 'uhc_doubles_', divisionId: 'uhc', name: 'UHC 2v2'},
		{id: 'uhc_four_', divisionId: 'uhc', name: 'UHC 4v4'},
		{id: 'uhc_meetup_', divisionId: 'uhc', name: 'UHC Deathmatch'},
		{id: 'op_duel_', divisionId: 'op',name: 'OP 1v1'},
		{id: 'op_doubles_', divisionId: 'op', name: 'OP 2v2'},
		{id: 'sw_duel_', divisionId: 'skywars', name: 'SkyWars 1v1'},
		{id: 'sw_doubles_', divisionId: 'skywars', name: 'SkyWars 2v2'},
		{id: 'bow_duel_', divisionId: 'bow', name: 'Bow 1v1'},
		{id: 'blitz_duel_', divisionId: 'blitz', name: 'Blitz 1v1'},
		{id: 'sumo_duel_', divisionId: 'sumo', name: 'Sumo 1v1'},
		{id: 'bowspleef_duel_', divisionId: 'tnt_games', name: 'Bow Spleef 1v1'},
		{id: 'classic_duel_', divisionId: 'classic', name: 'Classic 1v1'},
		{id: 'potion_duel_', divisionId: 'no_debuff', name: 'NoDebuff 1v1'},
		{id: 'combo_duel_', divisionId: 'combo', name: 'Combo 1v1'},
		{id: 'bridge_duel_', divisionId: 'bridge', name: 'Bridge 1v1'},
		{id: 'bridge_doubles_', divisionId: 'bridge', name: 'Bridge 2v2'},
		{id: 'bridge_2v2v2v2_', divisionId: 'bridge', name: 'Bridge 2v2v2v2'},
		{id: 'bridge_3v3v3v3_', divisionId: 'bridge', name: 'Bridge 3v3v3v3'},
		{id: 'bridge_four_', divisionId: 'bridge', name: 'Bridge 4v4'},
		{id: '', divisionId: 'all_modes', name: 'Overall'},
	],
};