const DIVISION_REQUIREMENTS = [
	{ req: 0, step: 0, max: 5, name: 'None', id: 'none', color: 'gray', style: '§7', bold: false },
	{ req: 50, step: 10, max: 5, name: 'Rookie', id: 'rookie', color: 'gray', style: '§7', bold: false },
	{ req: 100, step: 30, max: 5, name: 'Iron', id: 'iron', color: 'white', style: '§f', bold: false },
	{ req: 250, step: 50, max: 5, name: 'Gold', id: 'gold', color: 'gold', style: '§6', bold: false },
	{ req: 500, step: 100, max: 5, name: 'Diamond', id: 'diamond', color: 'darkaqua', style: '§3', bold: false },
	{ req: 1000, step: 200, max: 5, name: 'Master', id: 'master', color: 'darkgreen', style: '§2', bold: false },
	{ req: 2000, step: 600, max: 5, name: 'Legend', id: 'legend', color: 'darkred', style: '§4§l', bold: true },
	{ req: 5000, step: 1000, max: 5, name: 'Grandmaster', id: 'grandmaster', color: 'yellow', style: '§e§l', bold: true },
	{ req: 10000, step: 3000, max: 5, name: 'Godlike', id: 'godlike', color: 'purple', style: '§5§l', bold: true },
	{ req: 25000, step: 5000, max: 5, name: 'CELESTIAL', id: 'celestial', color: 'aqua', style: '§b§l', bold: true },
	{ req: 50000, step: 10000, max: 5, name: 'DIVINE', id: 'divine', color: 'pink', style: '§d§l', bold: true },
	{ req: 100000, step: 10000, max: 50, name: 'ASCENDED', id: 'ascended', color: 'red', style: '§c§l', bold: true },
];

const generateDivisions = (multiplier = 1) => DIVISION_REQUIREMENTS.map(div => ({
	...div,
	req: div.req * multiplier,
	step: div.step * multiplier,
}));

const REQUIREMENT_TYPES = {
	DEFAULT: 'default',
	HALF: 'half',
};

export const DUELS = {
	TITLE: 'Duels',
	REQUIREMENT_TYPES,
	DIVISIONS: {
		default: generateDivisions(1),
		half: generateDivisions(0.5),
		overall: generateDivisions(2),
	},
	ICONS: {
		none: '',
		strike: '⚡',
		heart: '❤',
		fists: 'ლ(ಠ_ಠლ)',
		podium: 'π',
		speed: '»',
		uninterested: '(T_T)',
		platforms: '...',
		sigma: 'Σ',
		biohazard: '☣',
		deny: '∅',
		sun: '❂',
		lucky: String.raw`\༼•◡•༽/`,
		fish: '><>',
		excited: '!!',
		arrow: '➜',
		reminiscence: '≈',
		beam: '——',
		layered: '≡',
		same_great_taste: 'ಠ_ಠ',
		pointy_star: '✵',
		victory: '༼つ°◡°༽つ',
		regretting_this: 'uwu',
		smiley: '^_^',
		rhythm: '♫♪',
		yin_and_yang: '☯',
		flower: '❀',
		repeated: '²',
		fancy_star: '✯',
		weight: '❚==❚',
		arena: 'Θ',
		confused: '??',
		div_ranking: '#X',
		snowman: '☃',
		final: '☠',
		gg: 'GG',
		star: '✫',
		walls: '÷',
		delta: 'δ',
		root: '√',
		fallen_crest: '☬',
		innocent: '{▀͜ʖ▀}',
		bear: 'ʕo͜oʔ',
		dont_blink: '-»[*_*]',
		dont_punch: '(°͜ʖ°)',
		alchemist: '<∅_∅>',
		wither: '[■_■]',
		bliss: '(°‿つ°)',
		flipper: '(┛ಠ_ಠ)┛彡┻━┻',
		boxer: "o=('-'Q)",
		piercing_look: '|> - <|',
		hypnotized: '[@~@]',
		ghost: 'ヘ(-w-ヘ)',
		reference: '{┳}',
		bill: '[($)]',
		smile_spam: ':)))))',
	},
	SCHEMES: {
		default: { type: 'default' },
		// solid 
		boilerplate_gold: { type: 'solid', color: '§6' },
		carpeted_light_purple: { type: 'solid', color: '§d' },
		vanilla_white: { type: 'solid', color: '§f' },
		absorption_yellow: { type: 'solid', color: '§e' },
		heavy_dark_green: { type: 'solid', color: '§2' },
		explosive_dark_red: { type: 'solid', color: '§4' },
		ender_green: { type: 'solid', color: '§a' },
		platformer_dark_purple: { type: 'solid', color: '§5' },
		armored_aqua: { type: 'solid', color: '§b' },
		pearl_dark_aqua: { type: 'solid', color: '§3' },
		withering_black: { type: 'solid', color: '§0' },
		persistent_dark_blue: { type: 'solid', color: '§1' },
		good_ol_gray: { type: 'solid', color: '§7' },
		punchable_red: { type: 'solid', color: '§c' },
		drawstring_dark_gray: { type: 'solid', color: '§8' },
		blitz_blue: { type: 'solid', color: '§9' },
		// gradient
		ultra_hardcore_undertone: { type: 'gradient', colors: ['§2', '§a', '§e', '§e', '§6'] },
		in_case_of_chroma: { type: 'gradient', colors: ['§5', '§d', '§f', '§9', '§1'] },
		elusive_jeremiah_huestring: { type: 'gradient', colors: ['§3', '§6', '§6', '§e', '§b'] },
		healthy_stain: { type: 'gradient', colors: ['§8', '§7', '§7', '§f', '§c'] },
		four_team_tie_dye: { type: 'gradient', colors: ['§e', '§a', '§f', '§c', '§9'] },
		combo_coating: { type: 'gradient', colors: ['§4', '§c', '§6', '§e', '§f'] },
		mythic_pigment: { type: 'gradient', colors: ['§c', '§e', '§a', '§b', '§d'] },
		picturesque_firework: { type: 'gradient', colors: ['§1', '§9', '§f', '§c', '§4'] },
		punching_paint: { type: 'gradient', colors: ['§4', '§5', '§5', '§d', '§b'] },
		flint_gradient: { type: 'gradient', colors: ['§f', '§f', '§7', '§8', '§0'] },
		a_splash_of_star: { type: 'gradient', colors: ['§1', '§9', '§3', '§3', '§b'] },
		sunny_shades: { type: 'gradient', colors: ['§3', '§b', '§b', '§f', '§e'] },
		blossoms: { type: 'gradient', colors: ['§5', '§d', '§f', '§d', '§f'] },
		festive_finish: { type: 'gradient', colors: ['§2', '§c', '§c', '§c', '§2'] },
		with_a_side_of_skies: { type: 'gradient', colors: ['§3', '§a', '§a', '§a', '§2'] },
		overpowered_gloss: { type: 'gradient', colors: ['§d', '§d', '§b', '§b', '§f'] },
		the_impossible_varnish: { type: 'gradient', colors: ['§d', '§a', '§a', '§a', '§f'] },
		color_of_a_flash: { type: 'gradient', colors: ['§8', '§f', '§f', '§f', '§8'] },
		bedding_hues: { type: 'gradient', colors: ['§c', '§c', '§c', '§f', '§f'] },
		variety_values: { type: 'gradient', colors: ['§b', '§f', '§f', '§f', '§b'] },
		og_fade: { type: 'gradient', colors: ['§6', '§e', '§f', '§7', '§8'] },
	},
	MODES: [
		// UHC
		{ id: 'uhc_duel', divisionId: 'uhc', name: 'UHC 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		{ id: 'uhc_doubles', divisionId: 'uhc', name: 'UHC 2v2', requirement: REQUIREMENT_TYPES.DEFAULT },
		{ id: 'uhc_four', divisionId: 'uhc', name: 'UHC 4v4', requirement: REQUIREMENT_TYPES.DEFAULT },
		{ id: 'uhc_meetup', divisionId: 'uhc', name: 'UHC Deathmatch', requirement: REQUIREMENT_TYPES.DEFAULT },
		// OP
		{ id: 'op_duel', divisionId: 'op', name: 'OP 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		{ id: 'op_doubles', divisionId: 'op', name: 'OP 2v2', requirement: REQUIREMENT_TYPES.DEFAULT },
		// SkyWars
		{ id: 'sw_duel', divisionId: 'skywars', name: 'SkyWars 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		{ id: 'sw_doubles', divisionId: 'skywars', name: 'SkyWars 2v2', requirement: REQUIREMENT_TYPES.DEFAULT },
		// 1v1
		{ id: 'bow_duel', divisionId: 'bow', name: 'Bow 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		{ id: 'blitz_duel', divisionId: 'blitz', name: 'Blitz 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		{ id: 'sumo_duel', divisionId: 'sumo', name: 'Sumo 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		{ id: 'combo_duel', divisionId: 'combo', name: 'Combo 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		{ id: 'quake_duel', divisionId: 'quakecraft', name: 'Quakecraft 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		// Classic
		{ id: 'classic_duel', divisionId: 'classic', name: 'Classic 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		{ id: 'classic_doubles', divisionId: 'classic', name: 'Classic 2v2', requirement: REQUIREMENT_TYPES.DEFAULT },
		// MegaWalls (half wins)
		{ id: 'mw_duel', divisionId: 'mega_walls', name: 'MegaWalls 1v1', requirement: REQUIREMENT_TYPES.HALF },
		{ id: 'mw_doubles', divisionId: 'mega_walls', name: 'MegaWalls 2v2', requirement: REQUIREMENT_TYPES.HALF },
		// misc half wins
		{ id: 'parkour_eight', divisionId: 'parkour', name: 'Parkour FFA', requirement: REQUIREMENT_TYPES.HALF },
		{ id: 'boxing_duel', divisionId: 'boxing', name: 'Boxing 1v1', requirement: REQUIREMENT_TYPES.HALF },
		{ id: 'potion_duel', divisionId: 'no_debuff', name: 'NoDebuff 1v1', requirement: REQUIREMENT_TYPES.HALF },
		// Bridge (half wins)
		{ id: 'bridge_duel', divisionId: 'bridge', name: 'Bridge 1v1', requirement: REQUIREMENT_TYPES.HALF },
		{ id: 'bridge_doubles', divisionId: 'bridge', name: 'Bridge 2v2', requirement: REQUIREMENT_TYPES.HALF },
		{ id: 'bridge_threes', divisionId: 'bridge', name: 'Bridge 3v3', requirement: REQUIREMENT_TYPES.HALF },
		{ id: 'bridge_four', divisionId: 'bridge', name: 'Bridge 4v4', requirement: REQUIREMENT_TYPES.HALF },
		{ id: 'bridge_2v2v2v2', divisionId: 'bridge', name: 'Bridge 2v2v2v2', requirement: REQUIREMENT_TYPES.HALF },
		{ id: 'bridge_3v3v3v3', divisionId: 'bridge', name: 'Bridge 3v3v3v3', requirement: REQUIREMENT_TYPES.HALF },
		{ id: 'capture_threes', divisionId: 'bridge', name: 'Bridge CTF 3v3', requirement: REQUIREMENT_TYPES.HALF },
		// Spleef 
		{ id: 'spleef_duel', divisionId: 'spleef', name: 'Spleef 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		{ id: 'bowspleef_duel', divisionId: 'spleef', name: 'Bow Spleef 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		// BedWars
		{ id: 'bedwars_two_one_duels', divisionId: 'bedwars', name: 'Bed Wars 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		{ id: 'bedwars_two_one_duels_rush', divisionId: 'bedwars', name: 'Bed Rush 1v1', requirement: REQUIREMENT_TYPES.DEFAULT },
		// Arena (no division)
		{ id: 'duel_arena', divisionId: '', name: 'Duel Arena', requirement: REQUIREMENT_TYPES.DEFAULT },
	],
};
