export const DUELS = {
	TITLE: 'Duels',
	DIVISIONS: [
		{name: 'Rookie',        id: 'rookie',       color: 'darkgray',  style: '§8' },
		{name: 'Iron',          id: 'iron',         color: 'white',     style: '§f' },
		{name: 'Gold',          id: 'gold',         color: 'gold',      style: '§6' },
		{name: 'Diamond',       id: 'diamond',      color: 'aqua',      style: '§b' },
		{name: 'Master',        id: 'master',       color: 'darkgreen', style: '§2' },
		{name: 'Legend',        id: 'legend',       color: 'darkred',   style: '§4§l' },
		{name: 'Grandmaster',   id: 'grandmaster',  color: 'yellow',    style: '§e§l' },
		{name: 'Godlike',       id: 'godlike',      color: 'purple',    style: '§5§l' },
		{name: 'WORLD ELITE',   id: 'world_elite',  color: 'aqua',      style: '§b§l' },
		{name: 'WORLD MASTER',  id: 'world_master', color: 'aqua',      style: '§b§l' },
		{name: 'WORLD\'S BEST', id: 'worlds_best',  color: 'aqua',      style: '§b§l' },
	],
	MODES: [
		{id: 'uhc_duel', divisionId: 'uhc', name: 'UHC 1v1'},
		{id: 'uhc_doubles', divisionId: 'uhc', name: 'UHC 2v2'},
		{id: 'uhc_four', divisionId: 'uhc', name: 'UHC 4v4'},
		{id: 'uhc_meetup', divisionId: 'uhc', name: 'UHC Deathmatch'},
		{id: 'op_duel', divisionId: 'op',name: 'OP 1v1'},
		{id: 'op_doubles', divisionId: 'op', name: 'OP 2v2'},
		{id: 'sw_duel', divisionId: 'skywars', name: 'SkyWars 1v1'},
		{id: 'sw_doubles', divisionId: 'skywars', name: 'SkyWars 2v2'},
		{id: 'bow_duel', divisionId: 'bow', name: 'Bow 1v1'},
		{id: 'blitz_duel', divisionId: 'blitz', name: 'Blitz 1v1'},
		{id: 'mw_duel', divisionId: 'mega_walls', name: 'MegaWalls'},
		{id: 'sumo_duel', divisionId: 'sumo', name: 'Sumo 1v1'},
		{id: 'bowspleef_duel', divisionId: 'tnt_games', name: 'Bow Spleef 1v1'},
		{id: 'parkour_eight', divisionId: 'parkour', name: 'Parkour FFA'},
		{id: 'boxing_duel', divisionId: 'boxing', name: 'Boxing 1v1'},
		{id: 'classic_duel', divisionId: 'classic', name: 'Classic 1v1'},
		{id: 'potion_duel', divisionId: 'no_debuff', name: 'NoDebuff 1v1'},
		{id: 'combo_duel', divisionId: 'combo', name: 'Combo 1v1'},
		{id: 'bridge_duel', divisionId: 'bridge', name: 'Bridge 1v1'},
		{id: 'bridge_doubles', divisionId: 'bridge', name: 'Bridge 2v2'},
		{id: 'bridge_threes', divisionId: 'bridge', name: 'Bridge 3v3'},
		{id: 'bridge_four', divisionId: 'bridge', name: 'Bridge 4v4'},
		{id: 'bridge_2v2v2v2', divisionId: 'bridge', name: 'Bridge 2v2v2v2'},
		{id: 'bridge_3v3v3v3', divisionId: 'bridge', name: 'Bridge 3v3v3v3'},
		{id: 'capture_threes', divisionId: 'bridge', name: 'Bridge CTF 3v3'},
	],
};