export const HYPIXEL = {
	GAMES : {
		ARENA: 'Arena Brawl',
		ARCADE: 'Arcade Games',
		BATTLEGROUND: 'Warlords',
		BEDWARS: 'Bed Wars',
		BUILD_BATTLE: 'Build Battle',
		DUELS: 'Duels',
		GINGERBREAD: 'Turbo Kart Racers',
		HOUSING: 'Housing',
		LEGACY: 'Classic Games',
		MAIN: 'Main',
		MCGO: 'Cops and Crims',
		MURDER_MYSTERY: 'Murder Mystery',
		PAINTBALL: 'Paintball',
		PIT: 'The Hypixel Pit',
		PROTOTYPE: 'Prototype',
		QUAKECRAFT: 'Quakecraft',
		SKYBLOCK: 'SkyBlock',
		SKYWARS: 'SkyWars',
		SPEED_UHC: 'Speed UHC',
		SUPER_SMASH: 'Smash Heroes',
		SURVIVAL_GAMES: 'Blitz SG',
		TNTGAMES: 'TNT Games',
		TOURNAMENT: 'Tournament Hall',
		UHC: 'UHC Champions',
		VAMPIREZ: 'VampireZ',
		WALLS: 'The Walls',
		WALLS3: 'Mega Walls',
	},
	MULTIPLIER: [
		{level: 0, value: 1},
		{level: 5, value: 1.5},
		{level: 10, value: 2},
		{level: 15, value: 2.5},
		{level: 20, value: 3},
		{level: 25, value: 3.5},
		{level: 30, value: 4},
		{level: 40, value: 4.5},
		{level: 50, value: 5},
		{level: 100, value: 5.5},
		{level: 125, value: 6},
		{level: 150, value: 6.5},
		{level: 200, value: 7},
		{level: 250, value: 8},
	],
	RANKMULTIPLIER: {
		VIP: {value: 2, name: 'VIP'},
		VIP_PLUS: {value: 3, name: 'VIP+'},
		MVP: {value: 4, name: 'MVP'},
		MVP_PLUS: {value: 5, name: 'MVP+'},
		YOUTUBER: {value: 7, name: 'YouTuber'},
	},
}