export const MURDERMYSTERY = {
	TITLE: 'Murder Mystery',
	// Infection mode has its own section
	MODES: [
		{id: '_MURDER_CLASSIC', name: 'Classic'},
		{id: '_MURDER_ASSASSINS', name: 'Assassins'},
		{id: '_MURDER_DOUBLE_UP', name: 'Double Up'},
		{id: '_MURDER_HARDCORE', name: 'Hardcore'},
		{id: '_MURDER_SHOWDOWN', name: 'Showdown'},
		{id: '', name: 'Overall'},
	],
	KNIFESKINS: {
		knife_skin_bone : "Big Bone",
		knife_skin_blaze_stick : "Blaze Rod",
		knife_skin_carrot_on_stick : "Carrot on a Stick",
		knife_skin_cheapo : "Cheapo Sword",
		knife_skin_cheese : "Cheese",
		knife_skin_chewed_bush : "Chewed Up Bush",
		knife_skin_diamond_shovel : "Only the Best",
		knife_skin_easter_basket : "Easter Basket",
		knife_skin_feather : "Feather",
		knife_skin_glistening_melon : "Glistening Melon",
		knife_skin_gold_digger : "Gold Digger",
		knife_skin_apple : "Healthy Treat",
		knife_skin_ice_shard: "Ice Shard",
		undefined : "Iron Sword",
		knife_skin_mouse_trap : "Mouse Trap",
		knife_skin_mvp : "MVP Diamond Sword",
		knife_skin_none : "Iron Sword",
		knife_skin_prickly : "Prickly",
		knife_skin_pumpkin_pie : "Pumpkin Pie",
		random_cosmetic : "Random",
		knife_skin_scythe : "Reaper Scythe",
		knife_skin_rudolphs_snack : "Rudolph's Favourite Snack",
		knife_skin_rudolphs_nose : "Rudolph's Nose",
		knife_skin_salmon : "Salmon",
		knife_skin_shears : "Shears",
		knife_skin_shovel : "Shovel",
		knife_skin_shiny_snack : "Sparkly Snack",
		knife_skin_stake : "Stake",
		knife_skin_stick : "Stick",
		knife_skin_stick_with_hat : "Stick with a Hat",
		knife_skin_sweet_treat : "Sweet Treat",
		knife_skin_timber : "Timber",
		knife_skin_vip : "VIP Gold Sword",
		knife_skin_wood_axe : "Wood Axe",
	},
}