export const PETS = {
	CONSUMABLES: [
		{ id: 'APPLE',         name: 'Apple'          },
		{ id: 'MELON',         name: 'Melon'          },
		{ id: 'PUMPKIN_PIE',   name: 'Pumpkin Pie'    },
		{ id: 'CARROT_ITEM',   name: 'Carrot'         },
		{ id: 'BAKED_POTATO',  name: 'Baked Potato'   },
		{ id: 'MUSHROOM_SOUP', name: 'Mushroom Soup'  },
		{ id: 'RED_ROSE',      name: 'Flower'         },
		{ id: 'HAY_BLOCK',     name: 'Hay'            },
		{ id: 'WHEAT',         name: 'Wheat'          },
		{ id: 'BREAD',         name: 'Bread'          },
		{ id: 'COOKIE',        name: 'Cookie'         },
		{ id: 'CAKE',          name: 'Cake'           },
		{ id: 'RAW_FISH',      name: 'Raw Fish'       },
		{ id: 'PORK',          name: 'Raw Porkchop'   },
		{ id: 'COOKED_BEEF',   name: 'Angus Steak'    },
		{ id: 'BONE',          name: 'Bone'           },
		{ id: 'ROTTEN_FLESH',  name: 'Rotten Flesh'   },
		{ id: 'MAGMA_CREAM',   name: 'Magma Cream'    },
		{ id: 'WATER_BUCKET',  name: 'Water'          },
		{ id: 'MILK_BUCKET',   name: 'Milk'           },
		{ id: 'LAVA_BUCKET',   name: 'Lava'           },
		{ id: 'STICK',         name: 'Stick'          },
		{ id: 'SLIME_BALL',    name: 'Ball'           },
		{ id: 'LEASH',         name: 'Leash'          },
		{ id: 'FEATHER',       name: 'Feather'        },
		{ id: 'GOLD_RECORD',   name: 'Frisbee'        },
		{ id: 'WOOD_SWORD',    name: 'Sparring Sword' },
	],
	PETS : {
		SILVERFISH               : { rarity: 'Common',     name: 'Silverfish',                 food: 'Cake',          drink: 'Water', exercise: 'Stick'          },

		CAT_BLACK                : { rarity: 'Common',     name: 'Black Cat',                  food: 'Raw Fish',      drink: 'Milk',  exercise: 'Ball'           },
		CAT_RED                  : { rarity: 'Common',     name: 'Red Cat',                    food: 'Raw Fish',      drink: 'Milk',  exercise: 'Ball'           },
		CAT_SIAMESE              : { rarity: 'Common',     name: 'Siamese Cat',                food: 'Raw Fish',      drink: 'Milk',  exercise: 'Ball'           },
		CAT_BLACK_BABY           : { rarity: 'Rare',       name: 'Black Cat (Baby)',           food: 'Cake',          drink: 'Milk',  exercise: 'Leash'          },
		CAT_RED_BABY             : { rarity: 'Rare',       name: 'Red Cat (Baby)',             food: 'Cake',          drink: 'Milk',  exercise: 'Leash'          },
		CAT_SIAMESE_BABY         : { rarity: 'Rare',       name: 'Siamese Cat (Baby)',         food: 'Cake',          drink: 'Milk',  exercise: 'Leash'          },
		WILD_OCELOT              : { rarity: 'Special',    name: 'Wild Ocelot',                food: 'Raw Fish',      drink: 'Milk',  exercise: 'Ball'           },
		WILD_OCELOT_BABY         : { rarity: 'Special',    name: 'Wild Ocelot (Baby)',         food: 'Raw Fish',      drink: 'Milk',  exercise: 'Leash'          },

		WOLF                     : { rarity: 'Common',     name: 'Wolf',                       food: 'Bone',          drink: 'Water', exercise: 'Leash'          },
		WOLF_BABY                : { rarity: 'Rare',       name: 'Wolf (Baby)',                food: 'Cookie',        drink: 'Milk',  exercise: 'Ball'           },

		BAT                      : { rarity: 'Epic',       name: 'Bat',                        food: 'Melon',         drink: 'Water', exercise: 'Stick'          },

		VILLAGER_BLACKSMITH      : { rarity: 'Rare',       name: 'Blacksmith Villager',        food: 'Angus Steak',   drink: 'Lava',  exercise: 'Sparring Sword' },
		VILLAGER_BLACKSMITH_BABY : { rarity: 'Epic',       name: 'Blacksmith Villager (Baby)', food: 'Pumpkin Pie',   drink: 'Milk',  exercise: 'Stick'          },
		VILLAGER_BUTCHER         : { rarity: 'Rare',       name: 'Butcher Villager',           food: 'Angus Steak',   drink: 'Lava',  exercise: 'Sparring Sword' },
		VILLAGER_BUTCHER_BABY    : { rarity: 'Epic',       name: 'Butcher Villager (Baby)',    food: 'Cookie',        drink: 'Milk',  exercise: 'Ball'           },
		VILLAGER_FARMER          : { rarity: 'Rare',       name: 'Farmer Villager',            food: 'Baked Potato',  drink: 'Milk',  exercise: 'Feather'        },
		VILLAGER_FARMER_BABY     : { rarity: 'Epic',       name: 'Farmer Villager (Baby)',     food: 'Cake',          drink: 'Milk',  exercise: 'Stick'          },
		VILLAGER_LIBRARIAN       : { rarity: 'Rare',       name: 'Librarian Villager',         food: 'Apple',         drink: 'Water', exercise: 'Frisbee'        },
		VILLAGER_LIBRARIAN_BABY  : { rarity: 'Epic',       name: 'Librarian Villager (Baby)',  food: 'Cookie',        drink: 'Milk',  exercise: 'Feather'        },
		VILLAGER_PRIEST          : { rarity: 'Rare',       name: 'Priest Villager',            food: 'Bread',         drink: 'Water', exercise: 'Frisbee'        },
		VILLAGER_PRIEST_BABY     : { rarity: 'Epic',       name: 'Priest Villager (Baby)',     food: 'Cake',          drink: 'Milk',  exercise: 'Feather'        },
		ZOMBIE_VILLAGER          : { rarity: 'Epic',       name: 'Zombie Villager',            food: 'Rotten Flesh',  drink: 'Lava',  exercise: 'Stick'          },
		WITCH                    : { rarity: 'Epic',       name: 'Witch',                      food: 'Pumpkin Pie',   drink: 'Milk',  exercise: 'Feather'        },

		ZOMBIE                   : { rarity: 'Common',     name: 'Zombie',                     food: 'Rotten Flesh',  drink: 'Lava',  exercise: 'Sparring Sword' },
		ZOMBIE_BABY              : { rarity: 'Rare',       name: 'Zombie (Baby)',              food: 'Cake',          drink: 'Milk',  exercise: 'Sparring Sword' },
		FROZEN_ZOMBIE            : { rarity: 'Epic',       name: 'Frozen Zombie',              food: '',              drink: '',      exercise: ''               },
		GROWING_ZOMBIE           : { rarity: 'Epic',       name: 'Growing Zombie',             food: '',              drink: '',      exercise: ''               },
		BURNING_ZOMBIE           : { rarity: 'Epic',       name: 'Burning Zombie',             food: '',              drink: '',      exercise: ''               },

		RED_HELPER               : { rarity: 'Epic',       name: 'Red Little Helper',          food: 'Cookie',        drink: 'Milk',  exercise: 'Frisbee'        },
		GREEN_HELPER             : { rarity: 'Epic',       name: 'Green Little Helper',        food: 'Cake',          drink: 'Milk',  exercise: 'Ball'           },

		IRON_GOLEM               : { rarity: 'Legendary',  name: 'Golem',                      food: 'Flower',        drink: 'Lava',  exercise: 'Ball'           },

		ENDERMAN                 : { rarity: 'Legendary',  name: 'Enderman',                   food: 'Baked Potato',  drink: 'Milk',  exercise: 'Ball'           },

		BLAZE                    : { rarity: 'Tournament', name: 'Blaze',                      food: 'Magma Cream',   drink: 'Lava',  exercise: 'Stick'          },

		SNOWMAN                  : { rarity: 'Legendary',  name: 'Snowman',                    food: 'Carrot',        drink: 'Water', exercise: 'Stick'          },

		HEROBRINE                : { rarity: 'Legendary',  name: 'Herobrine',                  food: 'Cookie',        drink: 'Milk',  exercise: 'Sparring Sword' },

		ENDERMITE                : { rarity: 'Legendary',  name: 'Endermite',                  food: 'None',          drink: 'Lava',  exercise: 'Sparring Sword' },

		MINI_WITHER              : { rarity: 'Legendary',  name: 'Mini Wither',                food: 'Rotten Flesh',  drink: 'Lava',  exercise: 'None'           },

		CLONE                    : { rarity: 'Tournament', name: 'Clone',                      food: 'Cake',          drink: 'Water', exercise: 'Sparring Sword' },

		MINECART                 : { rarity: 'Tournament', name: 'Minecart',                   food: 'Cake',          drink: 'Milk',  exercise: 'Sparring Sword' },

		TNT                      : { rarity: 'Tournament', name: 'TNT',                        food: '',              drink: '',      exercise: ''               },

		GRINCH                   : { rarity: 'Tournament', name: 'Grinch',                     food: 'Cookie',        drink: 'Lava',  exercise: 'Frisbee'        },

		BEE                      : { rarity: 'Legendary',  name: 'Bee',                        food: 'Flower',        drink: 'Water', exercise: 'Ball'           },

		FIREFLY                  : { rarity: 'Legendary',  name: 'Firefly',                    food: '',              drink: '',      exercise: ''               },

		CYCLOPS                  : { rarity: 'Legendary',  name: 'Cyclops',                    food: '',              drink: '',      exercise: ''               },

		SPIDER                   : { rarity: 'Epic',       name: 'Spider',                     food: '',              drink: 'Water', exercise: 'Leash'          },
		CAVE_SPIDER              : { rarity: 'Rare',       name: 'Cave Spider',                food: 'Angus Steak',   drink: 'Water', exercise: 'Sparring Sword' },
		BOUNCY_SPIDER            : { rarity: 'Legendary',  name: 'Bouncy Spider',              food: '',              drink: 'Water', exercise: 'Sparring Sword' },
		SPIDER_JOCKEY            : { rarity: 'Epic',       name: 'Spider Jockey',              food: '',              drink: '',      exercise: ''               },
		SNOWMAN_JOCKEY           : { rarity: 'Legendary',  name: 'Snowman Jockey',             food: '',              drink: '',      exercise: ''               },

		CHICKEN                  : { rarity: 'Common',     name: 'Chicken',                    food: 'Flower',        drink: 'Water', exercise: 'Frisbee'        },
		CHICKEN_BABY             : { rarity: 'Rare',       name: 'Chicken (Baby)',             food: 'Cookie',        drink: 'Milk',  exercise: 'Stick'          },
		CHICKEN_JOCKEY           : { rarity: 'Legendary',  name: 'Chicken Jockey',             food: '',              drink: '',      exercise: ''               },

		COW                      : { rarity: 'Common',     name: 'Cow',                        food: 'Wheat',         drink: 'Milk',  exercise: 'Feather'        },
		COW_BABY                 : { rarity: 'Rare',       name: 'Cow (Baby)',                 food: 'Cookie',        drink: 'Milk',  exercise: 'Ball'           },
		MOOSHROOM                : { rarity: 'Epic',       name: 'Mooshroom',                  food: 'Mushroom Soup', drink: 'Milk',  exercise: 'Feather'        },
		MOOSHROOM_BABY           : { rarity: 'Legendary',  name: 'Mooshroom (Baby)',           food: 'Cookie',        drink: 'Milk',  exercise: 'Feather'        },

		CREEPER                  : { rarity: 'Epic',       name: 'Creeper',                    food: 'Cake',          drink: 'Lava',  exercise: 'Leash'          },
		CREEPER_POWERED          : { rarity: 'Legendary',  name: 'Powered Creeper',            food: 'Cake',          drink: 'Lava',  exercise: 'Sparring Sword' },

		HORSE_BLACK              : { rarity: 'Epic',       name: 'Black Horse',                food: 'Apple',         drink: 'Water', exercise: 'Leash'          },
		HORSE_BROWN              : { rarity: 'Common',     name: 'Brown Horse',                food: 'Apple',         drink: 'Water', exercise: 'Leash'          },
		HORSE_CHESTNUT           : { rarity: 'Rare',       name: 'Chestnut Horse',             food: 'Apple',         drink: 'Water', exercise: 'Leash'          },
		HORSE_CREAMY             : { rarity: 'Rare',       name: 'Creamy Horse',               food: 'Apple',         drink: 'Water', exercise: 'Leash'          },
		HORSE_DARK_BROWN         : { rarity: 'Rare',       name: 'Dark Brown Horse',           food: 'Apple',         drink: 'Water', exercise: 'Leash'          },
		HORSE_GREY               : { rarity: 'Rare',       name: 'Gray Horse',                 food: 'Apple',         drink: 'Water', exercise: 'Leash'          },
		HORSE_WHITE              : { rarity: 'Epic',       name: 'White Horse',                food: 'Apple',         drink: 'Water', exercise: 'Leash'          },
		HORSE_BROWN_BABY         : { rarity: 'Rare',       name: 'Brown Horse (Baby)',         food: 'Apple',         drink: 'Milk',  exercise: 'Stick'          },
		BROWN_HORSE_BABY         : { rarity: 'Rare',       name: 'Brown Horse (Baby)',         food: 'Apple',         drink: 'Milk',  exercise: 'Stick'          },
		HORSE_CHESTNUT_BABY      : { rarity: 'Epic',       name: 'Chestnut Horse (Baby)',      food: 'Cake',          drink: 'Milk',  exercise: 'Leash'          },
		HORSE_CREAMY_BABY        : { rarity: 'Epic',       name: 'Creamy Horse (Baby)',        food: 'Cake',          drink: 'Milk',  exercise: 'Leash'          },
		HORSE_DARK_BROWN_BABY    : { rarity: 'Epic',       name: 'Dark Brown Horse (Baby)',    food: 'Cake',          drink: 'Milk',  exercise: 'Leash'          },
		HORSE_GRAY_BABY          : { rarity: 'Epic',       name: 'Gray Horse (Baby)',          food: 'Cake',          drink: 'Milk',  exercise: 'Leash'          },
		HORSE_UNDEAD             : { rarity: 'Epic',       name: 'Undead Horse',               food: 'Rotten Flesh',  drink: 'Lava',  exercise: 'Stick'          },
		HORSE_SKELETON           : { rarity: 'Legendary',  name: 'Skeleton Horse',             food: 'Rotten Flesh',  drink: 'Lava',  exercise: 'Stick'          },
		MULE                     : { rarity: 'Rare',       name: 'Mule',                       food: 'Hay',           drink: 'Water', exercise: 'Leash'          },
		DONKEY                   : { rarity: 'Rare',       name: 'Donkey',                     food: 'Hay',           drink: 'Water', exercise: 'Leash'          },

		PIG                      : { rarity: 'Common',     name: 'Pig',                        food: 'Apple',         drink: 'Water', exercise: 'Frisbee'        },
		PIG_BABY                 : { rarity: 'Rare',       name: 'Pig (Baby)',                 food: 'Apple',         drink: 'Milk',  exercise: 'Leash'          },
		PIG_ZOMBIE               : { rarity: 'Epic',       name: 'Pig Zombie',                 food: 'Melon',         drink: 'Lava',  exercise: 'Frisbee'        },
		PIG_ZOMBIE_BABY          : { rarity: 'Legendary',  name: 'Pig Zombie (Baby)',          food: 'Cookie',        drink: 'Milk',  exercise: 'Sparring Sword' },

		BLACK_RABBIT             : { rarity: 'Rare',       name: 'Black Rabbit',               food: 'Carrot',        drink: 'Water', exercise: 'Stick'          },
		BLACK_WHITE_RABBIT       : { rarity: 'Epic',       name: 'Black & White Rabbit',       food: 'Carrot',        drink: 'Water', exercise: 'Ball'           },
		BROWN_RABBIT             : { rarity: 'Rare',       name: 'Brown Rabbit',               food: 'Carrot',        drink: 'Water', exercise: 'Stick'          },
		GOLD_RABBIT              : { rarity: 'Epic',       name: 'Gold Rabbit',                food: 'Carrot',        drink: 'Water', exercise: 'Ball'           },
		SALT_PEPPER_RABBIT       : { rarity: 'Epic',       name: 'Salt & Pepper Rabbit',       food: 'Carrot',        drink: 'Water', exercise: 'Ball'           },
		WHITE_RABBIT             : { rarity: 'Rare',       name: 'White Rabbit',               food: 'Carrot',        drink: 'Water', exercise: 'Stick'          },
		KILLER_RABBIT            : { rarity: 'Epic',       name: 'Killer Rabbit',              food: '',              drink: 'None',  exercise: 'Sparring Sword' },
		RABBIT_JOCKEY            : { rarity: 'Legendary',  name: 'Rabbit Jockey',              food: '',              drink: '',      exercise: ''               },

		SHEEP_BLACK              : { rarity: 'Epic',       name: 'Black Sheep',                food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_BLACK_BABY         : { rarity: 'Legendary',  name: 'Black Sheep (Baby)',         food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_BLUE               : { rarity: 'Rare',       name: 'Blue Sheep',                 food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_BLUE_BABY          : { rarity: 'Epic',       name: 'Blue Sheep (Baby)',          food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_BROWN              : { rarity: 'Common',     name: 'Brown Sheep',                food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_BROWN_BABY         : { rarity: 'Rare',       name: 'Brown Sheep (Baby)',         food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_CYAN               : { rarity: 'Rare',       name: 'Cyan Sheep',                 food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_CYAN_BABY          : { rarity: 'Epic',       name: 'Cyan Sheep (Baby)',          food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_GRAY               : { rarity: 'Common',     name: 'Gray Sheep',                 food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_GRAY_BABY          : { rarity: 'Rare',       name: 'Gray Sheep (Baby)',          food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_GREEN              : { rarity: 'Rare',       name: 'Green Sheep',                food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_GREEN_BABY         : { rarity: 'Epic',       name: 'Green Sheep (Baby)',         food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_LIGHT_BLUE         : { rarity: 'Rare',       name: 'Light Blue Sheep',           food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_LIGHT_BLUE_BABY    : { rarity: 'Epic',       name: 'Light Blue Sheep (Baby)',    food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_LIME               : { rarity: 'Rare',       name: 'Lime Sheep',                 food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_LIME_BABY          : { rarity: 'Epic',       name: 'Lime Sheep (Baby)',          food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_MAGENTA            : { rarity: 'Rare',       name: 'Magenta Sheep',              food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_MAGENTA_BABY       : { rarity: 'Epic',       name: 'Magenta Sheep (Baby)',       food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_ORANGE             : { rarity: 'Rare',       name: 'Orange Sheep',               food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_ORANGE_BABY        : { rarity: 'Epic',       name: 'Orange Sheep (Baby)',        food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_PINK               : { rarity: 'Epic',       name: 'Pink Sheep',                 food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_PINK_BABY          : { rarity: 'Legendary',  name: 'Pink Sheep (Baby)',          food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_PURPLE             : { rarity: 'Rare',       name: 'Purple Sheep',               food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_PURPLE_BABY        : { rarity: 'Epic',       name: 'Purple Sheep (Baby)',        food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_RED                : { rarity: 'Rare',       name: 'Red Sheep',                  food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_RED_BABY           : { rarity: 'Epic',       name: 'Red Sheep (Baby)',           food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_SILVER             : { rarity: 'Common',     name: 'Silver Sheep',               food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_SILVER_BABY        : { rarity: 'Rare',       name: 'Silver Sheep (Baby)',        food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_WHITE              : { rarity: 'Common',     name: 'White Sheep',                food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_WHITE_BABY         : { rarity: 'Rare',       name: 'White Sheep (Baby)',         food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_YELLOW             : { rarity: 'Rare',       name: 'Yellow Sheep',               food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		SHEEP_YELLOW_BABY        : { rarity: 'Epic',       name: 'Yellow Sheep (Baby)',        food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },
		SHEEP_RAINBOW            : { rarity: 'Legendary',  name: 'Rainbow Sheep',              food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		BOUNCY_SHEEP             : { rarity: 'Epic',       name: 'Bouncy Sheep',               food: 'Wheat',         drink: 'Water', exercise: 'Leash'          },
		MERRY_SHEEP              : { rarity: 'Epic',       name: 'Merry Sheep',                food: 'Melon',         drink: 'Milk',  exercise: 'Frisbee'        },

		SLIME_BIG                : { rarity: 'Legendary',  name: 'Slime (Big)',                food: 'Bone',          drink: 'Milk',  exercise: 'Ball'           },
		SLIME_SMALL              : { rarity: 'Epic',       name: 'Slime (Small)',              food: 'Flower',        drink: 'Milk',  exercise: 'Stick'          },
		SLIME_TINY               : { rarity: 'Rare',       name: 'Slime (Tiny)',               food: 'Raw Fish',      drink: 'Milk',  exercise: 'Frisbee'        },
		MAGMA_CUBE_BIG           : { rarity: 'Legendary',  name: 'Magma Cube (Big)',           food: 'Magma Cream',   drink: 'Lava',  exercise: 'Feather'        },
		MAGMA_CUBE_SMALL         : { rarity: 'Epic',       name: 'Magma Cube (Small)',         food: 'Magma Cream',   drink: 'Lava',  exercise: 'Ball'           },
		MAGMA_CUBE_TINY          : { rarity: 'Epic',       name: 'Magma Cube (Tiny)',          food: 'Magma Cream',   drink: 'Milk',  exercise: 'Frisbee'        },

		SKELETON                 : { rarity: 'Epic',       name: 'Skeleton',                   food: 'Rotten Flesh',  drink: 'Lava',  exercise: 'Frisbee'        },
		WITHER_SKELETON          : { rarity: 'Tournament', name: 'Wither Skeleton',            food: 'None',          drink: 'Lava',  exercise: 'Sparring Sword' },
		FROZEN_SKELETON          : { rarity: 'Epic',       name: 'Frozen Skeleton',            food: 'Bone',          drink: 'Water', exercise: 'Ball'           },
		SMOLDERING_SKELETON      : { rarity: 'Epic',       name: 'Smoldering Skeleton',        food: 'Bone',          drink: 'None',  exercise: 'None'           },

		SQUID                    : { rarity: 'Special',    name: 'Squid',                      food: 'Raw Fish',      drink: 'Water', exercise: 'Frisbee'        },
		FLYING_SQUID             : { rarity: 'Legendary',  name: 'Flying Squid',               food: 'Raw Fish',      drink: 'Water', exercise: 'Frisbee'        },

		GUARDIAN                 : { rarity: 'Rare',       name: 'Guardian',                   food: 'Flower',        drink: 'Water', exercise: 'None'           },
		ELDER_GUARDIAN           : { rarity: 'Legendary',  name: 'Elder Guardian',             food: 'Flower',        drink: 'Water', exercise: 'None'           },

		FISH                     : { rarity: 'Epic',       name: 'Fish',                       food: '',              drink: '',      exercise: ''               },
		PUFFERFISH               : { rarity: 'Legendary',  name: 'Pufferfish',                 food: '',              drink: '',      exercise: ''               },
		SALMON                   : { rarity: 'Epic',       name: 'Salmon',                     food: '',              drink: '',      exercise: ''               },
		CLOWNFISH                : { rarity: 'Epic',       name: 'Clownfish',                  food: '',              drink: '',      exercise: ''               },

	},
	EXP: {
		"1":  0,     "2":  200,   "3":  210,   "4":  230,   "5":  250,   "6":  280,   "7":  310,   "8":  350,   "9":  390,   "10":  450,
		"11": 500,   "12": 570,   "13": 640,   "14": 710,   "15": 800,   "16": 880,   "17": 980,   "18": 1080,  "19": 1190,  "20":  1300,
		"21": 1420,  "22": 1540,  "23": 1670,  "24": 1810,  "25": 1950,  "26": 2100,  "27": 2260,  "28": 2420,  "29": 2580,  "30":  2760,
		"31": 2940,  "32": 3120,  "33": 3310,  "34": 3510,  "35": 3710,  "36": 3920,  "37": 4140,  "38": 4360,  "39": 4590,  "40":  4820,
		"41": 5060,  "42": 5310,  "43": 5560,  "44": 5820,  "45": 6090,  "46": 6360,  "47": 6630,  "48": 6920,  "49": 7210,  "50":  7500,
		"51": 7800,  "52": 8110,  "53": 8420,  "54": 8740,  "55": 9070,  "56": 9400,  "57": 9740,  "58": 10080, "59": 10430, "60":  10780,
		"61": 11150, "62": 11510, "63": 11890, "64": 12270, "65": 12650, "66": 13050, "67": 13440, "68": 13850, "69": 14260, "70":  14680,
		"71": 15100, "72": 15530, "73": 15960, "74": 16400, "75": 16850, "76": 17300, "77": 17760, "78": 18230, "79": 18700, "80":  19180,
		"81": 19660, "82": 20150, "83": 20640, "84": 21150, "85": 21650, "86": 22170, "87": 22690, "88": 23210, "89": 23750, "90":  24280,
		"91": 24830, "92": 25380, "93": 25930, "94": 26500, "95": 27070, "96": 27640, "97": 28220, "98": 28810, "99": 29400, "100": 30000, "101": Infinity
	},
	RARITY: {
		Common: 'green',
		Rare: 'blue',
		Epic: 'purple',
		Legendary: 'gold',
		Tournament: 'gold',
		Special: 'aqua',
	},
	HAPPINESS: [
		{value: 80, name: 'Super Happy', color: '§b'},
		{value: 50, name: 'Very Happy',  color: '§a'},
		{value: 20, name: 'Happy',       color: '§2'},
		{value: 0,  name: 'Okay',        color: '§e'},
	],
}