export const PETS = {
	CONSUMABLES: [
		{id: 'APPLE',         name: 'Apple'         },
		{id: 'MELON',         name: 'Melon'         },
		{id: 'PUMPKIN_PIE',   name: 'Pumpkin Pie'   },
		{id: 'CARROT_ITEM',   name: 'Carrot'        },
		{id: 'BAKED_POTATO',  name: 'Baked Potato'  },
		{id: 'MUSHROOM_SOUP', name: 'Mushroom Soup' },
		{id: 'RED_ROSE',      name: 'Flower'        },
		{id: 'HAY_BLOCK',     name: 'Hay'           },
		{id: 'WHEAT',         name: 'Wheat'         },
		{id: 'BREAD',         name: 'Bread'         },
		{id: 'COOKIE',        name: 'Cookie'        },
		{id: 'CAKE',          name: 'Cake'          },
		{id: 'RAW_FISH',      name: 'Raw Fish'      },
		{id: 'PORK',          name: 'Raw Porkchop'  },
		{id: 'COOKED_BEEF',   name: 'Angus Steak'   },
		{id: 'BONE',          name: 'Bone'          },
		{id: 'ROTTEN_FLESH',  name: 'Rotten Flesh'  },
		{id: 'MAGMA_CREAM',   name: 'Magma Cream'   },
		{id: 'WATER_BUCKET',  name: 'Water'         },
		{id: 'MILK_BUCKET',   name: 'Milk'          },
		{id: 'LAVA_BUCKET',   name: 'Lava'          },
		{id: 'STICK',         name: 'Stick'         },
		{id: 'SLIME_BALL',    name: 'Ball'          },
		{id: 'LEASH',         name: 'Leash'         },
		{id: 'FEATHER',       name: 'Feather'       },
		{id: 'GOLD_RECORD',   name: 'Frisbee'       },
		{id: 'WOOD_SWORD',    name: 'Sparring Sword'},
	],
}