export const SMASHHEROES = {
	TITLE: 'Smash Heroes',
	MODES: [
		{id: '_normal', name: '1v1v1v1'},
		{id: '_2v2', name: '2v2'},
		{id: '_teams', name: '2v2v2'},
		{id: '', name: 'Overall'},
	],
	HEROES: [
		{id: 'BOTMUN', name: 'Botmon', difficulty: 1},
		{id: 'THE_BULK', name: 'Bulk', difficulty: 2},
		{id: 'CAKE_MONSTER', name: 'Cake Monster', difficulty: 2},
		{id: 'FROSTY', name: 'Cryomancer', difficulty: 3},
		{id: 'GENERAL_CLUCK', name: 'General Cluck', difficulty: 1},
		{id: 'GREEN_HOOD', name: 'Green Hood', difficulty: 4},
		{id: 'GOKU', name: 'Karakot', difficulty: 3},
		{id: 'MARAUDER', name: 'Marauder', difficulty: 2},
		{id: 'PUG', name: 'Pug', difficulty: 2},
		{id: 'SANIC', name: 'Sanic', difficulty: 2},
		{id: 'SERGEANT_SHIELD', name: 'Sgt. Shield', difficulty: 3},
		{id: 'SHOOP_DA_WHOOP', name: 'Shoop', difficulty: 3},
		{id: 'SKULLFIRE', name: 'Skullfire', difficulty: 3},
		{id: 'SPODERMAN', name: 'Spooderman', difficulty: 4},
		{id: 'TINMAN', name: 'Tinman', difficulty: 1},
		{id: 'DUSK_CRAWLER', name: 'Void Crawler', difficulty: 2},
	],
	DIFFICULTY: ['green', 'yellow', 'red', 'darkred'],
	PRESTIGECOLORS: ['white', 'green', 'blue', 'purple', 'gold'],
}