export const TNTGAMES = {
	TITLE: 'TNT Games',
	WIZARDS: [
		{id: 'ancient', name: 'Ancient', color: 'gold'},
		{id: 'blood', name: 'Blood', color: 'darkred'},
		{id: 'fire', name: 'Fire', color: 'red'},
		{id: 'hydro', name: 'Hydro', color: 'darkblue'},
		{id: 'ice', name: 'Ice', color: 'blue'},
		{id: 'kinetic', name: 'Kinetic', color: 'pink'},
		{id: 'storm', name: 'Storm', color: 'yellow'},
		{id: 'toxic', name: 'Toxic', color: 'green'},
		{id: 'wither', name: 'Wither', color: 'black'},
	],
	RUN_PREFIXES: [
		{ req: 0, color: 'darkgray' },
		{ req: 25, color: 'gray' },
		{ req: 100, color: 'white' },
		{ req: 250, color: 'darkgreen' },
		{ req: 500, color: 'green' },
		{ req: 1000, color: 'blue' },
		{ req: 2500, color: 'purple' },
		{ req: 5000, color: 'gold' },
		{ req: 7500, color: 'red' },
		{ req: 10000, color: 'black' },
		{ req: 15000, color: 'rainbow' },
	],
	TAG_PREFIXES: [
		{ req: 0, color: 'darkgray' },
		{ req: 15, color: 'gray' },
		{ req: 50, color: 'white' },
		{ req: 100, color: 'darkgreen' },
		{ req: 250, color: 'green' },
		{ req: 500, color: 'blue' },
		{ req: 1000, color: 'purple' },
		{ req: 1500, color: 'gold' },
		{ req: 2500, color: 'red' },
		{ req: 5000, color: 'black' },
		{ req: 10000, color: 'rainbow' },
	],
}