export const TURBOKARTRACERS = {
	TITLE: 'Turbo Kart Racers',
	ATTRIBUTES: {
		ACCELERATION: 'Acceleration',
		BOOSTER_SPEED: 'Booster Speed',
		BRAKES: 'Brakes',
		DRIFTING_EFFICIENCY: 'Drifting Efficiency',
		HANDLING: 'Handling',
		RECOVERY: 'Recovery',
		START_POSITION: 'Start Position',
		TOP_SPEED: 'Top Speed',
		TRACTION: 'Traction',
	},
	QUALITY: [
		{name: 'Starter', color: 'gray'},
		{name: 'Mini', color: 'gray'},
		{name: 'Auxiliary', color: 'green'},
		{name: 'Standard', color: 'green'},
		{name: 'Primary', color: 'green'},
		{name: 'Experimental', color: 'green'},
		{name: 'Dynamic', color: 'blue'},
		{name: 'Stellar', color: 'blue'},
		{name: 'Kinetic', color: 'blue'},
		{name: 'Multi-phase', color: 'blue'},
		{name: 'Turbocharged', color: 'pink'},
		{name: 'Quantum', color: 'pink'},
		{name: 'Superluminal', color: 'pink'},
		{name: 'Psi', color: 'pink'},
		{name: 'Eternal', color: 'purple'},
	],
	RARITY: {
		BASIC: 'Basic',
		SUPER: 'Super',
		AWESOME: 'Awesome',
	}
}