export const TURBOKARTRACERS = {
	TITLE: 'Turbo Kart Racers',
	ATTRIBUTES: {
		ACCELERATION: 'Acceleration',
		BOOSTER_SPEED: 'Booster Speed',
		BRAKES: 'Brakes',
		DRIFTING_EFFICIENCY: 'Drifting Efficiency',
		HANDLING: 'Handling',
		RECOVERY: 'Recovery',
		START_POSITION: 'Start Position',
		TOP_SPEED: 'Top Speed',
		TRACTION: 'Traction',
	},
	QUALITY: [
		{name: 'Starter', color: 'gray'},
		{name: 'Mini', color: 'gray'},
		{name: 'Auxiliary', color: 'green'},
		{name: 'Standard', color: 'green'},
		{name: 'Primary', color: 'green'},
		{name: 'Experimental', color: 'green'},
		{name: 'Dynamic', color: 'blue'},
		{name: 'Stellar', color: 'blue'},
		{name: 'Kinetic', color: 'blue'},
		{name: 'Multi-phase', color: 'blue'},
		{name: 'Turbocharged', color: 'pink'},
		{name: 'Quantum', color: 'pink'},
		{name: 'Superluminal', color: 'pink'},
		{name: 'Psi', color: 'pink'},
		{name: 'Eternal', color: 'purple'},
	],
	RARITY: {
		BASIC: 'Basic',
		SUPER: 'Super',
		AWESOME: 'Awesome',
	},
	PREFIXES: [
		{ req: 0, color: 'darkgray', emblem: '✪' },
		{ req: 5, color: 'gray', emblem: '✪' },
		{ req: 25, color: 'white', emblem: '✪' },
		{ req: 50, color: 'aqua', emblem: '✪' },
		{ req: 100, color: 'green', emblem: '✪' },
		{ req: 200, color: 'yellow', emblem: '✪' },
		{ req: 300, color: 'blue', emblem: '✪' },
		{ req: 400, color: 'pink', emblem: '✪' },
		{ req: 500, color: 'gold', emblem: '✪' },
		{ req: 750, color: 'darkgreen', emblem: '✪' },
		{ req: 1000, color: 'darkblue', emblem: '✪' },
		{ req: 2500, color: 'purple', emblem: '✪' },
		{ req: 5000, color: 'darkred', emblem: '✪' },
		{ req: 10000, color: 'black', emblem: '✪' },
	],
}