export const VAMPIREZ = {
	TITLE: 'VampireZ',
	HUMAN_PREFIXES: [
		{ req: 0, color: 'darkgray' },
		{ req: 20, color: 'gray' },
		{ req: 50, color: 'white' },
		{ req: 100, color: 'gold' },
		{ req: 150, color: 'yellow' },
		{ req: 200, color: 'darkgreen' },
		{ req: 250, color: 'green' },
		{ req: 300, color: 'purple' },
		{ req: 500, color: 'pink' },
		{ req: 750, color: 'darkblue' },
		{ req: 1000, color: 'darkblue', bold: true },
		{ req: 1500, color: 'blue', bold: true },
		{ req: 2000, color: 'darkaqua', bold: true },
		{ req: 2500, color: 'aqua', bold: true },
		{ req: 3000, color: 'red', bold: true },
		{ req: 5000, color: 'darkred', bold: true },
		{ req: 10000, color: 'black', bold: true },
		{ req: 15000, color: 'rainbow' },
	],
	VAMPIRE_PREFIXES: [
		{ req: 0, color: 'darkgray' },
		{ req: 50, color: 'white' },
		{ req: 100, color: 'yellow' },
		{ req: 250, color: 'green' },
		{ req: 500, color: 'pink' },
		{ req: 750, color: 'aqua' },
		{ req: 1000, color: 'red' },
		{ req: 1500, color: 'gold' },
		{ req: 2000, color: 'darkaqua' },
		{ req: 2500, color: 'green' },
		{ req: 3000, color: 'darkgreen' },
		{ req: 5000, color: 'blue' },
		{ req: 7500, color: 'darkblue' },
		{ req: 10000, color: 'darkblue', bold: true },
		{ req: 20000, color: 'darkred' },
		{ req: 30000, color: 'darkred', bold: true },
		{ req: 40000, color: 'purple', bold: true },
		{ req: 50000, color: 'black', bold: true },
		{ req: 100000, color: 'rainbow' },
	],
}