export const APP = {
	appName: "25Karma",
	appNickname : "+25 Karma!",
	appURL: "",
	API: "",
	documentTitle: "25Karma",
	hypixelForums: "",
	hypixelStatusPage: "https://status.hypixel.net/",
	nameMC: "https://namemc.com/search?q=",
	organization: "https://github.com/25karma",
	ownerName: "",
	skyblock: "https://sky.shiiyu.moe/",
	suggestedPlayers: ["Technoblade", "gamerboy80", "Technoblade"],
	supportURL: "",
}